stages:
  - plan
  - apply

include:
 - project: 'terra_test/terra_test'
   file: 'gitlab-template/terraform.gitlab-ci.yml'


before_script:
  - echo $deployer > /tmp/gcp_credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_credentials.json"
  - apt-get update -qy
  - apt-get install -y unzip
  - curl -sSL https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip -o /tmp/terraform.zip
  - unzip /tmp/terraform.zip -d /usr/local/bin/
  - chmod +x /usr/local/bin/terraform
  - cd terraform


terraform_planning:
   stage: plan
   extends:
    - .plan

terraform_applying:
  stage: apply
  extends:
    - .terra_apply
